# Generated by Django 3.1.5 on 2021-01-15 18:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_auto_20210115_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontact',
            name='block_list',
            field=models.ManyToManyField(blank=True, related_name='block_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercontact',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='contacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
