# Generated by Django 3.1.5 on 2021-01-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_remove_usercontact_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontact',
            name='block_list',
            field=models.ManyToManyField(blank=True, related_name='block_list', to='chat.ChatRoom'),
        ),
    ]
