# Generated by Django 3.1.5 on 2021-01-15 21:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0009_auto_20210116_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontact',
            name='block_list',
            field=models.ManyToManyField(blank=True, related_name='block_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
