# Generated by Django 3.1.5 on 2021-01-15 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_auto_20210116_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroommessage',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
